config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homepage#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  authenticate :user do
    namespace :users do
      resources :appointments, only: %i[index show create]
      resource :profile, only: %i[show]
    end
  end
  devise_for :doctors, skip: [:registrations]
  devise_scope :doctor do
    get 'doctors/edit' => 'doctors/registrations#edit', :as => 'edit_doctor_registration'
    patch 'doctors' => 'doctors/registrations#update', :as => 'doctor_registration'
  end
  authenticate :doctor do
    namespace :doctors do
      resources :appointments, only: %i[index show edit update]
      resources :pacients, only: %i[index show]
      resource :profile, only: %i[show]
    end
  end
  %w[404 422 500].each do |code|
    match "/#{code}", to: 'errors#show', code: code, via: :all
  end
  resources :doctors, only: %i[index]
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  include ImageUploader::Attachment(:image)

  devise :database_authenticatable, :rememberable, authentication_keys: [:phone_number]

  validates :phone_number, presence: true,
                           uniqueness: { allow_blank: true, if: :phone_number_changed? },
                           length: { minimum: Constants::Account::PHONE_NUMBER_MIN_SIZE,
                                     maximum: Constants::Account::PHONE_NUMBER_MAX_SIZE },
                           format: { with: Constants::Account::PHONE_NUMBER_REGEXP,
                                     allow_blank: true,
                                     if: :phone_number_changed? }
  validates :password, presence: { on: :create },
                       confirmation: { on: :create },
                       length: { in: Constants::Account::PASSWORD_LENGTH,
                                 if: :encrypted_password_changed? }
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :expirience, numericality: { only_integer: true }

  belongs_to :category
  has_many :appointments, dependent: :destroy
  has_many :pacients, through: :appointments, source: :user
end

app/controllers/doctors/appointments_controller.rb
# frozen_string_literal: true

module Doctors
  class AppointmentsController < ApplicationController
    before_action :set_appointment!, except: :index
    authorize_resource

    def index
      @appointments = current_doctor.appointments.where(status: params[:status])
      @pagy, @appointments = pagy(@appointments, items: Constants::Shared::ITEMS_PER_PAGE)
    end

    def show; end

    def edit; end

    def update
      if @appointment.update(permitted_params)
        @appointment.closed!
        redirect_to doctors_appointments_path(status: 'closed'), notice: t('.appointment_updated')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_appointment!
      @appointment = current_doctor.appointments.find(params[:id])
    end

    def permitted_params
      params.require(:appointment).permit(:body)
    end
  end
end

app/controllers/doctors/pacients_controller.rb
# frozen_string_literal: true

module Doctors
  class PacientsController < ApplicationController
    authorize_resource class: false
    authorize_resource class: 'Appointment'

    def index
      @pagy, @pacients = pagy(current_doctor.pacients, items: Constants::Shared::ITEMS_PER_PAGE)
    end

    def show
      @pacient = current_doctor.pacients.find(params[:id])
      @appointments = @pacient.appointments.where(doctor_id: current_doctor.id)
      @pagy, @appointments = pagy(@appointments, items: Constants::Shared::ITEMS_PER_PAGE)
    end
  end
end

app/controllers/doctors/profiles_controller.rb
# frozen_string_literal: true

module Doctors
  class ProfilesController < ApplicationController
    def show
      authorize! :read, current_doctor
    end
  end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

module Doctors
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    protected

    def update_resource(resource, params)
      if params[:password].present? || params[:current_password].present?
        resource.update_with_password(params)
      else
        params.delete(:current_password)
        resource.update_without_password(params)
      end
    end

    def configure_permitted_parameters
      allowed = %i[phone_number name password current_password image expirience description workplace workplace_address]
      devise_parameter_sanitizer.permit(:account_update, keys: allowed)
    end

    def after_update_path_for(_resource)
      doctors_profile_path
    end
  end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  before_action :set_category, only: :index
  authorize_resource

  def index
    @pagy, @doctors = pagy(filtered_doctors, items: Constants::Shared::ITEMS_PER_PAGE)
    @doctors = @doctors.decorate
  end

  private

  def set_category
    @category = @categories.find_by(id: params[:category_id])
  end

  def filtered_doctors
    @category.blank? ? Doctor.all : @category.doctors
  end
end

app/views/doctors/pacients/_pacient_appointments.haml
%table.table
  %thead
    %tr
      %th{scope: "col"}= t('.number')
      %th{scope: "col"}= t('.status')
      %th{scope: "col"}= t('.created_date')
      %th{scope: "col"}= t('.action')
  %tbody
    - appointments.each do |appointment|
      %tr
        %th{scope: "row"}= appointment.id
        %td= t(".#{appointment.status}")
        %td= appointment.created_at.strftime('%R %B %d, %Y')
        - if appointment.active? 
          %td= link_to 'Give a prescription', edit_doctors_appointment_path(appointment), class: 'btn btn-link'
        - if appointment.closed? 
          %td= link_to 'Show a prescription', doctors_appointment_path(appointment), class: 'btn btn-link'

app/views/doctors/pacients/_pacients_table.haml
%table.table
  %thead
    %tr
      %th{scope: "col"}= t('.pacient_name')
      %th{scope: "col"}= t('.action')
  %tbody
    - pacients.each do |pacient|
      %tr
        %td{scope: "row"}= pacient.name
        %td= link_to t('.show'), doctors_pacient_path(pacient), class: 'btn btn-link'

app/views/doctors/pacients/index.haml
.bg-light.py-5.my-2
  %h2.text-center.text-primary= t('.pacients')
.mb-4
  .row.justify-content-md-center
    .col-8.text-center
      = render 'pacients_table', pacients: @pacients
    - if @pagy.pages > 1
      .col-10.justify-content-center.pagination
        != pagy_bootstrap_nav @pagy

app/views/doctors/pacients/show.haml
.bg-light.py-5.my-2
  %h2.text-center.text-primary= t('.pacient_card', name: @pacient.name)
.mb-4
  .row.justify-content-md-center
    .col-12.text-center
      %h3= t('.appointments')
      = render 'pacient_appointments', appointments: @appointments
    - if @pagy.pages > 1
      .col-10.justify-content-center.pagination
        != pagy_bootstrap_nav @pagy