config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homepage#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  authenticate :user do
    namespace :users do
      resources :appointments, only: %i[index show create]
      resource :profile, only: %i[show]
    end
  end
  devise_for :doctors, skip: [:registrations]
  devise_scope :doctor do
    get 'doctors/edit' => 'doctors/registrations#edit', :as => 'edit_doctor_registration'
    patch 'doctors' => 'doctors/registrations#update', :as => 'doctor_registration'
  end
  authenticate :doctor do
    namespace :doctors do
      resources :appointments, only: %i[index show edit update]
      resources :pacients, only: %i[index show]
      resource :profile, only: %i[show]
    end
  end
  %w[404 422 500].each do |code|
    match "/#{code}", to: 'errors#show', code: code, via: :all
  end
  resources :doctors, only: %i[index]
end

app/views/partials/_flash_messages.haml
- flash.each do |name, msg|
  = content_tag :div, msg, id: "flash_#{name}", class: "container alert #{flash_class(name)}"

app/views/partials/_footer.haml
%footer.bg-light
  .container.d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4
    .col-md-4.d-flex.align-items-center
      = link_to root_path, class: 'mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1 home-link' do
        =image_tag 'logo.png', size: '30'
        %span.mb-3.mb-md-0.text-muted= t('.company')
    %ul.nav.col-md-4.justify-content-end.list-unstyled.d-flex
      %li.ms-3
        =link_to '#', class: 'text-muted' do
          %i.bi.bi-twitter.fs-3.text-body
      %li.ms-3
        =link_to '#', class: 'text-muted' do
          %i.bi.bi-facebook.fs-3.text-body
      %li.ms-3
        =link_to '#', class: 'text-muted' do
          %i.bi.bi-instagram.fs-3.text-body

app/views/partials/_head.haml
%head
  %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %title CodicaTestcase
  %meta{content: "width=device-width,initial-scale=1", name: "viewport"}
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload"
  = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  = favicon_link_tag 'favicon.png', type: 'image/png'

app/views/partials/_header.haml
%header
  %nav.navbar.navbar-expand-lg.bg-light
    .container
      .navbar-header  
        %a.navbar-brand{href: "#"}= t('.site_title')
      #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
        %ul.navbar-nav
          %li.nav-item
            = link_to t('.home_link'), root_path, class: 'nav-link active home-link'
          %li.nav-item.dropdown
            = link_to t('.categories_link'), '#',
                aria: {expanded: false},
                data: {'bs-toggle': 'dropdown'}, role: 'button',
                class: 'categories-link nav-link dropdown-toggle'
            %ul.dropdown-menu.categories-menu
              = link_to t('.all_categories'), doctors_path,  class: 'dropdown-item all-categories'
              - categories.each do |category|
                %li= link_to "#{category.title}", doctors_path(category_id: category.id),
                  class: 'dropdown-item ctegory-link'
          - if account_signed_in?
            %li.nav-item.dropdown
              = link_to current_account.name, '#',
                  aria: {expanded: false, haspopup: true},
                  data: {'bs-toggle': 'dropdown'}, role: 'button',
                  class: 'account-menu-button nav-link dropdown-toggle'
              %ul.dropdown-menu.account-menu#doctor-account
                - if doctor_signed_in?
                  %li= link_to t('.pacients'),
                    public_send("#{current_account.class.name.pluralize.downcase}_pacients_path"),
                    class: 'pacients-link dropdown-item'
                %li= link_to t('.appointments'),
                  { controller: "#{current_account.class.name.pluralize.downcase}/appointments", status: 'active' },
                  class: 'appointments-link dropdown-item'
                %li= link_to t('.profile'),
                  public_send("#{current_account.class.name.pluralize.downcase}_profile_path"),
                  class: 'profile-link dropdown-item'
                %li.divider{ role: 'separator' }
                %li= button_to t('.logout'),
                  destroy_session_path(current_account), method: :delete,
                  class: 'logout-button dropdown-item', form_class: 'logout-form'
          - else
            %li.nav-item.dropdown
              = link_to t('.login'), '#',
                  aria: {expanded: false, haspopup: true},
                  data: {'bs-toggle': 'dropdown'}, role: 'button',
                  class: 'login-menu-button nav-link dropdown-toggle'
              %ul.dropdown-menu.login-menu
                %li= link_to t('.login_as_doctor'), new_doctor_session_path, class: 'login-doctor-link dropdown-item'
                %li= link_to t('.login_as_pacient'), new_user_session_path, class: 'login-pacient-link dropdown-item'
            %li.nav-item
              = link_to t('.sign_up'), new_user_registration_path, class: 'sign-up-link nav-link'