config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homepage#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  authenticate :user do
    namespace :users do
      resources :appointments, only: %i[index show create]
      resource :profile, only: %i[show]
    end
  end
  devise_for :doctors, skip: [:registrations]
  devise_scope :doctor do
    get 'doctors/edit' => 'doctors/registrations#edit', :as => 'edit_doctor_registration'
    patch 'doctors' => 'doctors/registrations#update', :as => 'doctor_registration'
  end
  authenticate :doctor do
    namespace :doctors do
      resources :appointments, only: %i[index show edit update]
      resources :pacients, only: %i[index show]
      resource :profile, only: %i[show]
    end
  end
  %w[404 422 500].each do |code|
    match "/#{code}", to: 'errors#show', code: code, via: :all
  end
  resources :doctors, only: %i[index]
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor

  enum :status, { active: 0, closed: 1 }

  validates :body, presence: { on: :update }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, authentication_keys: [:phone_number]

  validates :phone_number, presence: true,
                           uniqueness: { allow_blank: true, if: :phone_number_changed? },
                           length: { minimum: Constants::Account::PHONE_NUMBER_MIN_SIZE,
                                     maximum: Constants::Account::PHONE_NUMBER_MAX_SIZE },
                           format: { with: Constants::Account::PHONE_NUMBER_REGEXP,
                                     allow_blank: true,
                                     if: :phone_number_changed? }
  validates :password, presence: { on: :create },
                       confirmation: { on: :create },
                       length: { in: Constants::Account::PASSWORD_LENGTH,
                                 if: :encrypted_password_changed? }
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments
end

app/controllers/doctors/appointments_controller.rb
# frozen_string_literal: true

module Doctors
  class AppointmentsController < ApplicationController
    before_action :set_appointment!, except: :index
    authorize_resource

    def index
      @appointments = current_doctor.appointments.where(status: params[:status])
      @pagy, @appointments = pagy(@appointments, items: Constants::Shared::ITEMS_PER_PAGE)
    end

    def show; end

    def edit; end

    def update
      if @appointment.update(permitted_params)
        @appointment.closed!
        redirect_to doctors_appointments_path(status: 'closed'), notice: t('.appointment_updated')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_appointment!
      @appointment = current_doctor.appointments.find(params[:id])
    end

    def permitted_params
      params.require(:appointment).permit(:body)
    end
  end
end

app/controllers/users/appointments_controller.rb
# frozen_string_literal: true

module Users
  class AppointmentsController < ApplicationController
    authorize_resource

    def index
      @appointments = current_user.appointments.where(status: params[:status])
      @pagy, @appointments = pagy(@appointments, items: Constants::Shared::ITEMS_PER_PAGE)
    end

    def show
      @appointment = current_user.appointments.closed.find(params[:id])
    end

    def create
      if active_appointment_exists?
        redirect_back_or_to doctors_path, alert: t('.appointment_exists')
      elsif appointments_count_reached?
        redirect_back_or_to doctors_path, alert: t('.appointments_count_reached')
      elsif current_user.appointments.create(permitted_params)
        redirect_to users_appointments_path(status: 'active'), notice: t('.appointment_created')
      else
        redirect_to root_path, status: :unprocessable_entity
      end
    end

    private

    def active_appointment_exists?
      current_user.appointments.where(doctor_id: params[:doctor_id]).active.present?
    end

    def appointments_count_reached?
      find_doctor!.appointments.active.count >= Constants::Shared::MAX_DOCTOR_APPOINTMENT_COUNT
    end

    def find_doctor!
      Doctor.find(params[:doctor_id])
    end

    def permitted_params
      params.permit(:doctor_id)
    end
  end
end

app/controllers/users/profiles_controller.rb
# frozen_string_literal: true

module Users
  class ProfilesController < ApplicationController
    def show
      authorize! :read, current_user
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    include DevisePermittedParameters

    protected

    def update_resource(resource, params)
      if params[:password].present? || params[:current_password].present?
        resource.update_with_password(params)
      else
        params.delete(:current_password)
        resource.update_without_password(params)
      end
    end

    def after_update_path_for(_resource)
      users_profile_path
    end
  end
end

app/views/users/appointments/_appointments_table.haml
%table.table
  %thead
    %tr
      %th{scope: "col"}= t('.number')
      %th{scope: "col"}= t('.doctor_name')
      %th{scope: "col"}= t('.created_date')
      - if request.params[:status] == 'closed' 
        %th{scope: "col"}= t('.action')
  %tbody
    - appointments.each do |appointment|
      %tr
        %th{scope: "row"}= appointment.id
        %td= appointment.doctor.name
        %td= appointment.created_at.strftime('%R %B %d, %Y')
        - if request.params[:status] == 'closed' 
          %td= link_to 'Show a prescription', users_appointment_path(appointment), class: 'btn btn-link'

app/views/users/appointments/index.haml
.bg-light.py-5.my-2
  %h2.text-center.text-primary= t(".#{request.params[:status]}_appointments")
.mb-4
  .row.justify-content-md-center
    .col-10
      %ul.nav.nav-tabs.justify-content-md-center.nav-fill
        %li.nav-item
          = link_to t('.active_appointments'), users_appointments_path(status: 'active'),
            class: "nav-link #{ 'active' if request.params[:status] == 'active' }", aria: { 'current': 'page' } 
        %li.nav-item
          = link_to t('.closed_appointments'), users_appointments_path(status: 'closed'),
            class: "nav-link #{ 'active' if request.params[:status] == 'closed' }" 
      = render 'appointments_table', appointments: @appointments
    - if @pagy.pages > 1
      .col-10.justify-content-center.pagination
        != pagy_bootstrap_nav @pagy

app/views/users/appointments/show.haml
.bg-light.py-5.my-2
  %h2.text-center.text-primary= t('.appointment_to', name: @appointment.doctor.name)
.row.justify-content-center.bg-light.py-3.my-3
  .col-10
    .row
      .col-12.text-center
        %h3= t('.prescription')
    .row.appointment-card.my-4.bg-white.py-3.shadow-sm.border.rounded
      .col-9
        .prescription-label.d-flex
          %p= @appointment.body
    .col-12.text-center
      = link_to t('.back'), :back, class: 'btn btn-primary'